apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: equipos-service
build:
  artifacts:
    - image: jandresmartinez/equipos
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ../k8s/equipos.yaml
