apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: gateway-service
build:
  artifacts:
    - image: jandresmartinez/gateway
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ../k8s/gateway.yaml
