apiVersion: apps/v1
kind: Deployment
metadata:
  name: division
  labels:
    app: division
spec:
  replicas: 1
  selector:
    matchLabels:
      app: division
  template:
    metadata:
      labels:
        app: division
    spec:
      containers:
      - name: division
        image: jandresmartinez/division
        ports:
        - containerPort: 8080
        readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: host
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: port
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: division
  labels:
    app: division
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: division