apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: default
      containers:
      - name: gateway
        image: jandresmartinez/gateway
        ports:
        - containerPort: 8995
        readinessProbe:
            httpGet:
              port: 8995
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
        livenessProbe:
            httpGet:
              port: 8995
              path: /actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5        
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    spring-boot: "true"
spec:
  ports:
  - port: 8995
    protocol: TCP
    targetPort: 8995
  selector:
    app: gateway
  type: NodePort