apiVersion: apps/v1
kind: Deployment
metadata:
  name: jugadores
  labels:
    app: jugadores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jugadores
  template:
    metadata:
      labels:
        app: jugadores
    spec:
      containers:
      - name: jugadores
        image: jandresmartinez/jugadores
        ports:
        - containerPort: 5000               
---
apiVersion: v1
kind: Service
metadata:
  name: jugadores
  labels:
    app: jugadores    
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: jugadores
  type: NodePort