apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: liga-service
build:
  artifacts:
    - image: jandresmartinez/liga
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ../k8s/liga.yaml
