apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: division-service
build:
  artifacts:
    - image: jandresmartinez/division
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - ../k8s/division.yaml
